### ISSUE TITLE
Some Feedback

### ISSUE THREAD

**Issue by rotzfrech** [pjmagee/dota2-helper#16]
Hello, greetings from Vienna,

first of all thanks for the I guess so pretty powerful dota timer.

I am truly a coding noob, so the not all of the following statements/potential improvements have to be true:

- Why is there no ReadMe.txt in the folder?
- Why do the Instructions tell you to "create" the gamestate_integration_d2helper.cfg instead of telling you, that this file is in the main folder and just needs to be copied?
- Why does the instructions dont tell you to add the launch command -gamestateintegration to dota? its disabled by default says dota wiki
- the tormenter sound shook me off my seat the first 2 games
- Why is the appsettings.json so badly formattad AND the order of the items is different than in the program?
- everytime i start the program new, all the sounds are disabled?
- in appsettings.json: what means: "ismanualreset" and "isenabled" and "isit"?
- (wrong) I want maybe one more stack timer (depending on distance to camp to move to camp)
- (wrong)I truly want one or two PULL timers - thats what i miss now
- some of the audios are veeeery meaningless, like a bing or some thing
- maybe an option after which time a timer isnt announced any more (after 15 min u dont pull)
- i just now understand that "GSI" means gamestateintegration
- different profiles  would be extranice, playing offlane and safelane has very different timings

I hope i didnt forgot something. Thanks for your work.

greetings

edit: after playing with the appsettings.json, i am able to add new timers, i also did some text to speech mp3 online, YAY

**Comment by pjmagee** [comment]
`Why is the appsettings.json so badly formattad AND the order of the items is different than in the program?`

- This was a save file serialisation issue, ive fixed this. Now when it re-writes your changes, it formats the file so it's not all on 1 line compressed. The ordering, im not sure. The ordering, not sure.

**Comment by pjmagee** [comment]
Hello, i worked a lot on changing the application, i will not be able to patch the old one anymore. I will close this issue for now and thanks for the feedback!

**Comment by rotzfrech** [comment]
bro(and I never use that word), I just installed your new Version and at
first glance I like it much much more...
The loading screen is superp, so i know its alive..
It took me 1-2 mins to figure out, that just by clicking the profile under
the "profiles" tab i select it for Timers. I was looking to select the
profile in the timers tab, double click just edits the text - or maybe my
thinking is wrong.
And you need at least four default profiles, each team savelane/offlane
plus one for mid but havent tested the default timers yet...
And its pretty hard to find out where(where you have to click) to download
the program, the instructions half a meter text later isnt linked - the
possible user want to click download and check it out.
And I was telling a friend about our story and wanted to show him your tool
and I just wasnt able to find it in the internet (but didnt remember the
exact name "helper" because its more a timing tool /
programmabklealter tool whatever

just my thoughts, I hope you can work with them

...testing...

see you,
Michael

Am Sa., 23. Nov. 2024 um 21:33 Uhr schrieb Patrick Magee <
***@***.***>:
